KANJI_OVERRIDES = {
    "万": "ten thousand",
    "刀": "sword; knife; scalpel",
    "月": "moon; month; Monday",
    "火": "fire; Tuesday",
    "水": "water; Wednesday",
    "木": "tree; wood; Thursday",
    "金": "gold; metal; Friday",
    "土": "earth; ground; Saturday",
    "日": "sun; day; Japan; Sunday",
    "男": "man; male",
    "目": "eye",
    "田": "rice field",
    "門": "gate",
    "戸": "door",
    "車": "car; vehicle",
    "的": "target; in the manner of",
    "無": "nothingness; none; without",
    "迦": "ka (used phonetically)",
    "元": "origin; former; starting point",
    "原": "meadow; original; raw",
    "源": "source of a flow; origin",
    "自": "self; one's own; automatically",
    "身": "physical self; status; body",
    "尺": "Japanese foot; measure",
    "寸": "Japanese inch; measure; a little",
    "者": "someone; person; -er",
    "先": "ahead; earlier; tip",
    "前": "in front; before; past",
    "後": "behind; after; future",
    "事": "thing (abstract); matter; fact",
    "物": "thing (physical); object; matter",
    "対": "face to face; opposite; even",
    "又": "again; also; on the other hand",
    "俺": "I (male); myself",
    "信": "belief; trust; faith",
    "様": "honorific suffix; Esq.; manner",
    "達": "accomplished; reach; plural for people",
    "代": "generation; era; substitute",
    "違": "differ; wrong; mistake",
    "表": "surface; express; chart",
    "解": "untie; solve; explain",
    "行": "go; do; conduct",
    "経": "pass; manage; sutra",
    "計": "measure; calculate; plan",
    "道": "road; path; district",
    "通": "pass through; traffic; connection",
    "階": "storey; stair; counter for storeys",
    "集": "gather; meet; collect",
    "料": "fee; material; ingredient",
    "感": "sense; feeling; impression",
    "直": "straight; direct; immediate",
    "過": "overdo; exceed; lapse",
    "真": "true; reality; genuine",
    "基": "fundamentals; foundation",
    "応": "respond; comply; apply",
    "参": "participate; attend; join",
    "然": "thus; as such; natural",
    "台": "pedestal; a stand; counter for machines",
    "軽": "light; trifling; unimportant",
    "員": "member; employee; number",
    "役": "role; duty; labour",
    "申": "report; submit; humble",
    "技": "skill; technique; craft",
    "吿": "report; inform; accuse",
    "京": "capital",
    "兆": "omen; 10**12 (trillion)",
    "緒": "beginning; connection; inception",
    "再": "again; reoccur; anew",
    "観": "view; observe; outlook",
    "構": "structure; set up; mind",
    "張": "stretch; tension; spread",
    "管": "pipe; manage; control",
    "両": "both",
    "検": "inspect; test; verify",
    "調": "investigate; look into; adjust",
    "収": "receive; collect; reap",
    "治": "govern; settle; cure",
    "規": "rule; standard; measure",
    "防": "ward off; defend against; protect",
    "営": "operate; manage; camp",
    "探": "search; seek; explore",
    "注": "pour; note; attention",
    "回": "number of times counter; round",
    "脚": "leg; undercarriage",
    "共": "together; both",
    "更": "change; renew; further",
    "葱": "spring onion; scallion",
    "西": "west",
    "粥": "congee; rice porridge",
    "拉": "ramen",
    "蕎": "soba; buckwheat",
    "饂": "udon",
    "鱈": "cod",
    "鰯": "sardine",
    "巳": "sign of the snake; 9-11AM",
    "条": "article; clause; counter for paragraphs",
    "旬": "ten-day period; season (for products)",
    "辰": "sign of the dragon; 7-9AM",
    "寅": "sign of the tiger; 3-5AM",
    "騎": "equestrian; riding on horses",
    "険": "inaccessible place; steep place",
    "訓": "instruction; Japanese character reading",
    "秦": "Manchu dynasty; naturalized foreigner",
    "枚": "counter for flat thin objects or sheets",
    "賛": "approve; praise; inscription",
    "征": "subjugate; collect taxes",
    "鎮": "tranquilize; suppress",
    "煎": "decoct; infuse; simmer",
    "炒": "stir-fr; sauté",
    "捉": "grasp; seize",
    "竣": "completion (of construction)",
    "祐": "aid (blessing)",
    "輔": "assist; support",
    "栖": "inhabit; dwell (animal)",
    "魄": "vital spirit; anima",
    "牡": "male (animal)",
    "沙": "fine sand; sediment",
    "楊": "poplar",
    "個": "individual; counter for items"
}

READING_OVERRIDES = {
    ("私", "わたくし"): "わたし",
    ("何", "なん"): "なに",
    ("皆", "みな"): "みんな",
    ("明日", "あす"): "あした",
    ("富士山", "ふじやま"): "ふじさん",
    ("茸", "たけ"): "きのこ",
}

TRANSLATION_OVERRIDES = {  # note katakana
    ("大学", "ダイガク"): "university; college; former imperial university of Japan",
    ("息子", "ムスコ"): "son",
    ("一", "イチ"): "one; 1",
    ("火", "ヒ"): "fire; flame",
    ("火災", "カサイ"): "fire (as a destructive event); blaze",
    ("土", "ツチ"): "soil; earth; ground",
    ("土産", "ミヤゲ"): "local speciality or souvenir bought while travelling as a gift for others",
    ("彼女", "カノジョ"): "she; her; girlfriend",
    ("万", "マン"): "ten thousand; 10,000; myriad",
    ("出る", "デル"): "to leave; to move forward",
    ("先", "サキ"): "point ahead; destination; ahead (or first) in a sequence",
    ("万歳", "バンザイ"): "hurray; ten thousand years (of life or happiness)",
    ("見える", "ミエル"): "to be seen; to be visible; to look",
    ("年間", "ネンカン"): "years (period of)",
    ("週間", "シュウカン"): "weeks (period of)",
    ("秒速", "ビョウソク"): "speed (per second); instant; velocity (per second)",
    ("速度", "ソクド"): "speed; velocity",
    ("課題", "カダイ"): "task; homework; project",
    ("場所", "バショ"): "place (specific); location; room",
    ("所", "トコロ"): "place (general or abstract); spot; scene",
    ("関する", "カンスル"): "to concern with; to be related",
    ("焦点", "ショウテン"): "focus (optics); focal point; point of attention",
    ("回", "カイ"): "a time; number of times counter; inning (baseball)",
    ("関係", "カンケイ"): "relation; involvement; connection",
    ("世界", "セカイ"): "the world; sphere; humanity",
    ("様", "サマ"): "honorific suffix",
    ("死", "シ"): "death; (an) out; death penalty",

    ("通", "トオリ"): "passage; traffic; flow (of water, air, etc.)",
    ("別", "ベツ"): "separate; different; distinction",
    ("等", "トウ"): "etc.; and the like; rank",
    ("一番", "イチバン"): "number one; best; first",
    ("少", "スコシ"): "a little; a bit; slightly",
    ("少ない", "スクナイ"): "not many; not much; few",
    ("過ぎる", "スギル"): "to be in excess; to pass in time; to pass through",
    ("過ごす", "スゴス"): "to spend (time); to overdo; to take care of",
    ("共", "トモ"): "together; together with; mutual",
    ("変", "ヘン"): "weird; strange; change",
    ("富士山", "フジサン"): "Mount Fuji; Mt. Fuji",
    ("甲子園", "コウシエン"): "Koshien Stadium; National High School Baseball Tournament",
    ("兆", "チョウ"): "sign; omen; 10**12",
    ("運転", "ウンテン"): "driving (of a vehicle); operation (of a machine); working",
    ("緊張", "キンチョウ"): "tension; nervousness; strain",
    ("風", "カゼ"): "wind; breeze",
    ("検討", "ケントウ"): "consideration; examination; review",
    ("他", "ホカ"): "other; another",
    
    # GPT5.1 corrections:
    ("十二", "ジュウニ"): "twelve; 12",
    ("二十五", "ニジュウゴ"): "twenty-five; 25",
    ("二十六", "ニジュウロク"): "twenty-six; 26",
    ("二十八", "ニジュウハチ"): "twenty-eight; 28",
    ("二十九", "ニジュウキュウ"): "twenty-nine; 29",
    ("二十七", "ニジュウナナ"): "twenty-seven; 27",
    ("三十", "サンジュウ"): "thirty; 30",
    ("十三", "ジュウサン"): "thirteen; 13",
    ("五百", "ゴヒャク"): "five hundred; 500",
    ("七五三", "シチゴサン"): "Shichi-Go-San festival",
    ("七", "ナナ"): "seven; 7",
    ("七草", "ナナクサ"): "seven spring herbs",
    ("十", "ジュウ"): "ten; 10",
    ("十分", "ジップン"): "ten minutes",
    ("十一", "ジュウイチ"): "eleven; 11",
    ("百万", "ヒャクマン"): "one million; million",
    ("百合", "ユリ"): "lily (Lilium spp.); yuri",
    ("千億", "センオク"): "one hundred billion; 100 billion",
    ("大丈夫", "ダイジョウブ"): "all right; OK; no problem",
    ("男", "ナン"): "male; man",
    ("山", "サン"): "Mt.; Mount",
    ("足止め", "アシドメ"): "preventing someone from leaving; being stranded",
    ("猫耳", "ネコミミ"): "cat ears (costume); nekomimi",
    ("青山", "アオヤマ"): "green mountain",
    ("大石", "オオイシ"): "large stone; boulder",
    ("生", "セイ"): "life; birth; living",
    ("先生", "センセイ"): "teacher; master; expert",
    ("先生", "センセー"): "teacher; master; expert",
    ("生(い)かす", "イカス"): "to make the best use of; to let live",
    ("午后", "ゴゴ"): "afternoon; p.m.",
    ("午餐", "ゴサン"): "lunch",
    ("牛(ぎゅう)タン", "ギュウタン"): "beef tongue",
    ("牛(ぎゅう)すじ", "ギュウスジ"): "beef tendon",
    ("入(い)り", "イリ"): "entry; entering",
    ("入(い)り口(ぐち)", "イリグチ"): "entrance",
    ("見込(みこ)み", "ミコミ"): "expectation; prospects",
    ("貝合(かいあ)わせ", "カイアワセ"): "shell-matching game",
    ("豆(まめ)", "マメ"): "legume; bean",
    ("豆(まめ)まき", "マメマキ"): "bean-scattering",
    ("又聞(またぎ)き", "マタギキ"): "hearsay",
    ("令", "レイ"): "order; command",
    ("今(こん)", "コン"): "the present; this",
    ("十分", "ジュウブン"): "enough; sufficient; plenty",
    ("時々", "トキドキ"): "sometimes; at times",
    ("美味(おい)しい", "オイシイ"): "delicious; tasty",
    ("美味(うま)い", "ウマイ"): "delicious; tasty",
    ("美味(びみ)", "ビミ"): "delicacy; good flavor",
    ("知(し)れる", "シレル"): "to become known; to be known",
    ("作(つく)る", "ツクル"): "to make; to create; to prepare",
    ("作(つく)り", "ツクリ"): "making; build; appearance",
    ("実装(じっそう)", "ジッソウ"): "implementation; installation",
    ("定(さだ)める", "サダメル"): "to decide; to determine",
    ("一定", "イッテイ"): "fixed; set; standardized",
    ("体(からだ)", "カラダ"): "body",
    ("一体(いったい)", "イッタイ"): "one object; one body",
    ("高(だか)", "ダカ"): "amount; sum",
    ("無(な)い", "ナイ"): "nonexistent; not there; without",
    ("大変", "タイヘン"): "very; serious; difficult",
    ("必死", "ヒッシ"): "desperate; frantic; frantic effort",
    ("第", "ダイ"): "ordinal; number prefix",
    ("快", "カイ"): "pleasure; delight",
    ("野菜", "ヤサイ"): "vegetable",
    ("切れる", "キレル"): "to snap; to expire; to run out",
    ("相変", "アイカワラズ"): "as usual; as always",
    ("他愛", "タアイ"): "silliness; childishness",
    ("次", "ジ"): "next (prefix); hypo-",
    ("置き換える", "オキカエル"): "to replace; to swap; to transpose",
    ("縁起", "エンギ"): "omen; luck; origin",
    ("置き去り", "オキザリ"): "leaving behind; abandonment",
    ("海人", "カイジン"): "fisherman; diver",
    ("格好", "カッコウ"): "appearance; shape; form",
    ("均等", "キントウ"): "equal; even; uniform",
    ("対等", "タイトウ"): "equal footing; equality; equal terms",
    ("定める", "サダメル"): "to decide; to fix; to establish",
    ("等", "ヒトシイ"): "equal; identical",
    ("島", "トウ"): "island",
    ("式", "シキ"): "ceremony; style; formula",
    ("素", "ソ"): "element; plain; raw",
    ("南京", "ナンキン"): "Nanjing; Nanking",
    ("安価", "アンカ"): "low-priced; cheap",
    ("頑張る", "ガンバル"): "to persevere; to do one's best",
    ("羊歯", "シダ"): "fern",
    ("朝日新聞社", "アサヒシンブンシャ"): "The Asahi Shimbun Company",
    ("カ氏", "シ"): "Fahrenheit",
    ("境内", "ケイダイ"): "shrine/temple grounds",
    ("深セン", "シンセン"): "Shenzhen",
    ("藤本", "トウホン"): "climbing plant; vine",
    ("撮す", "ウツス"): "to photograph; to film",
    ("嫌い", "キライ"): "dislike; hate",
    ("機嫌", "キゲン"): "mood; temper",
    ("ご機嫌", "ゴキゲン"): "mood; good spirits",
    ("遊星", "ユウセイ"): "asteroid; minor planet",
    ("大森", "オオモリ"): "Ōmori (place name)",
    ("二刀流", "ニトウリュウ"): "two-sword style; using two swords; dual wielding",
    ("気軽", "キガル"): "casual; carefree; lighthearted",
    ("数字", "スウジ"): "numeral; digit; figure",
    ("人数", "ニンズウ"): "number of people",
    ("洗う", "アラウ"): "to wash; to cleanse",
    ("聞ける", "キケル"): "to be able to hear; to be able to ask",
    ("得", "トク"): "profit; advantage",
    ("優勝", "ユウショウ"): "overall victory; championship",
    ("大規模", "ダイキボ"): "large-scale",
    ("群像", "グンゾウ"): "group portrait; group of characters; group",
    ("非", "ヒ"): "fault; wrong; injustice",
    ("丸太", "マルタ"): "log",
    ("馬鹿", "バカ"): "idiot; foolish; absurd",
    ("独特", "ドクトク"): "unique; distinctive",
    ("普通", "フツウ"): "ordinary; normal; local train",
    ("敵う", "カナウ"): "to rival; to match; to equal",
    ("創る", "ツクル"): "to create; to found; to make",
    ("奥", "オク"): "inner part; depths; wife's quarters",
    ("拡張", "カクチョウ"): "expansion; extension",
    ("毛皮", "ケガワ"): "fur; pelt",
    ("粉", "コナ"): "powder; flour",
    ("杉内", "スギウチ"): "surname; place name",
    ("涙", "ナミダ"): "tear; tears",
    ("湿", "シツ"): "moisture; humidity",
    ("飯綱", "イイヅナ"): "Iizuna (mountain; deity)",
    ("弁慶", "ベンケイ"): "Benkei (legendary warrior monk); utensil stand",
    ("徐", "オモムロ"): "slowly; deliberately",
    ("蝶番", "チョウツガイ"): "hinge",
    ("蝶つがい", "チョウツガイ"): "hinge",
    ("后", "キサキ"): "empress; queen",
    ("瞳", "ヒトミ"): "pupil (of the eye); eye(s)",
    ("蓮", "ハス"): "lotus; sacred lotus",
    ("胸糞", "ムナクソ"): "disgust; revulsion",
    ("溜飲", "リュウイン"): "acid reflux; bile; pent-up resentment",
    ("噌", "ソ"): "miso",
    ("虹", "ニジ"): "rainbow",
    ("尖圭", "センケイ"): "condyloma; genital warts",
    ("勃勃", "ボツボツ"): "gradually; bit by bit",
    ("賓辞", "ヒンジ"): "postmodifier; attributive element",
    ("陀", "ダ"): "Buddhist transliteration element",
    ("嘛", "マ"): "modal particle; emphatic particle",
    ("海石榴", "ツバキ"): "camellia",
    ("睨", "ゲイ"): "glare; stare",
    ("漸々", "ゼンゼン"): "gradually; little by little",
    ("香料", "コウリョウ"): "fragrance; flavoring; seasoning",
    ("服役", "フクエキ"): "imprisonment; serving a sentence",
    ("充分", "ジュウブン"): "enough; sufficient; plenty",
    ("沖", "オキ"): "open sea; offing",
    ("劇", "ゲキ"): "drama; play",
    ("訓戒", "クンカイ"): "admonition; warning; reprimand",
    ("手札", "シュサツ"): "hand (of cards); cards in hand",
    ("胸くそ", "ムナクソ"): "disgust; irritation; resentment",
    ("誠", "マコト"): "sincerity; truth; honesty",
    ("陶磁", "トウジ"): "ceramics; pottery; porcelain",
    ("沼", "ヌマ"): "marsh; swamp; bog",
    ("挨拶回り", "アイサツマワリ"): "courtesy call; making the rounds",
    ("掴まる", "ツカマル"): "to be caught; to hold on to; to get (e.g. a taxi)",
    ("煮やす", "ニヤス"): "easy to boil; easy to cook",
    ("別荘", "ベッソウ"): "vacation home; holiday house",
    ("炉", "ロ"): "hearth; furnace; kiln",
    ("鋼", "コウ"): "steel; sword steel",
    ("粗熱", "アラネツ"): "residual heat; heat remaining after cooking",
    ("点滴", "テンテキ"): "IV drip; intravenous infusion",
    ("洪", "コウ"): "Hong (surname)",
    ("柏", "カシワ"): "oak",
    ("尺八", "シャクハチ"): "shakuhachi; end-blown bamboo flute",
    ("苑", "エン"): "garden; park",
    ("葵", "アオイ"): "mallow; hollyhock",
    ("耶", "ヤ"): "interrogative particle; phonetic use",
    ("老翁", "ロウオウ"): "old man",
    ("舵輪", "ダリン"): "helm; steering wheel",
    ("詣る", "マイル"): "to make a pilgrimage; to visit a shrine or temple",
    ("姑息", "コソク"): "makeshift; ad hoc; stopgap",
}

# Rarer than top 2.5k and not jouyou, written rarely but read often (eg on menus)
DONT_DROP_ME = [
    "鮪", "鮭", "鯖", "鰤", "鰹", "鰯", "鯵", "蛸", "烏", "老", "蟹", "鰻", "穴", "鱈", "帆", "鰆", "蛤", "粥", "葱", "茸", "饂"
]

TOP_KANJI_ORDER = [
    "一", "二", "三", "四", "五", "六", "七", "八", "九", "十", "百", "千", "万", "円",
    "月", "火", "水", "木", "金", "土", "日", "曜",
    "人", "大", "小",
    "男", "女", "父", "母", "子",
    "口", "手", "足", "目", "耳", "心",
    "左", "右", "石", "山", "川", "虫", "竹", "米", "田",
    "車", "王", "工", "丁", "門","戸", 
    "刀", "力", "方",
    "白", "皿", "巾",
    "入", "出", "立", "行", "下", "上", "止", "正", "生", "牛", "午", "半", "平",
    "言", "見", "貝", "豆", "糸", "文", "又", "夕",
    "本", "末", "未", "夫", "天", "矢", "欠",
    "至", "良", "長", "斤", "尺", "寸", "可", 
]

SIMILAR_KANJI_GROUPS = [
    # Same-concept group and I don't want to leave it to frequency order
    ["自", "身", "者"],
    ["億", "兆"],
    ["前", "先", "去", "後"],
    ["年", "週", "時", "分","秒"],  # leaving out some which are in the TOP_KANJI_ORDER set - I think it's ambiguous for a kanji to be in both
    ["春", "香", "夏", "秋", "冬"],
    ["東", "西", "北", "南"],
    ["外", "内"],
    ["明", "昨"],
    ["思", "意", "感", "想", "念"],
    ["青", "赤", "黄", "黒", "茶", "緑", "紫", "桃", "橙", "紺", "灰", "銀"],
    ["村", "町", "区", "市", "都", "府", "県", "郡"],
    ["員", "委", "役", "課", "局", "庁", "省", "署", "官"],
    ["番", "号"],
    ["所", "場"],
    ["研", "究"],
    ["犬", "猫", "魚", "鳥", "馬", "羊", "豚", "鶏", "肉"],
    ["鮪", "鮭", "鯵", "鯖", "鰹", "鰤", "蟹", "鰻", "蛸", "鱈", "鰯", "鰆", "蛤", "烏", "老", "穴", "帆"],
    ["通", "道"],
    ["朝", "昼", "夜"],
    ["話", "語", "読", "書"],
    ["弟", "姉", "兄", "妹"],
    ["家", "店", "屋",],
    ["古", "早"],
    ["髪", "顔", "鼻", "歯", "舌", "喉", "首"],
    ["肩", "胸", "背", "腹", "腰", "腸", "尻"],
    ["腕", "肘", "掌", "指", "脚", "膝", "踵"],
    ["肌", "血", "骨"],
    ["野", "菜", "葱", "芋", "茸"],
    ["飯", "膳", "弁", "丼", "餅", "粥", "汁"],
    ["焼", "炙", "炊", "炒", "揚", "煮", "蒸", "油", "粉", "卵"],
    ["麺", "蕎", "饂", "拉"],
    ["初", "始"],
    ["返", "帰"],
    ["代", "変", "替"],
    ["雨", "雲", "雪", "雷", "霧", "霜", "雹", "露"],
    ["晴", "曇", "陰", "風", "嵐"],
    ["熱", "暑", "暖", "涼", "冷", "寒", "湿", "乾"],
    ["守", "防"],
    ["個", "枚", "回", "階", "冊", "台", "匹", "頭", "羽"],
    ["在", "存"],

    # Visually similar
    # ["土", "士"],  actually lets give a bit of breathing space for day 1
    # ["日", "曰"],
    # ["牛", "午", "生"],
    # ["人", "入"],  # In the TOP_KANJI_ORDER already
    # ["万", "方"],
    # ["刀", "力"],
    # ["右", "石"],
    # ["上", "止", "正"],
    # ["千", "干"],
    ["士", "干", "曰"],
    ["己", "已"],
    ["失", "朱"],
    ["今", "会", "合", "命", "令"],
    ["申", "由", "甲"],
    ["元", "原", "源"],
    ["体", "休"],
    ["爪", "瓜"],
    ["幸", "辛"],
    ["間", "聞"],
    ["采", "釆"],
    ["募", "寡"],
    ["史", "更", "使", "便"],
    ["友", "反"],
    ["業", "美"],
    ["法", "洗", "流"],
    ["名", "各"],
    ["待", "持"],
    ["每", "海"],
    ["職", "識"],
    ["坂", "板"],
    ["治", "冶"],
    ["陸", "睦"],
    ["沢", "況"],
    ["択", "釈"],
    ["鏡", "鐘"],
    ["挙", "拳"],
    ["塵", "鹿"],
    ["決", "快"],
    ["具", "真"],
    ["丈", "才"],
    ["料", "科"],
    ["貨", "貿", "賃"],
    ["河", "洞"],
    ["散", "撒"],
    ["輸", "輪"],
    ["険", "除"],
    ["鋭", "鈍"],
    ["務", "疑"],
    ["績", "積"],
    ["給", "絵"],
    ["豊", "曹"],
    ["船", "航"],
]

JLPT_LEVELS = {
    "人": 5, "一": 5, "日": 5, "大": 5, "年": 5, "出": 5, "本": 5, "中": 5, "子": 5, "見": 5, "国": 5, "上": 5, "分": 5, "生": 5, "行": 5, "二": 5, "間": 5, "時": 5, "気": 5, "十": 5, "女": 5, "三": 5, "前": 5, "入": 5, "小": 5, "後": 5, "長": 5, "下": 5, "学": 5, "月": 5, "何": 5, "来": 5, "話": 5, "山": 5, "高": 5, "今": 5, "書": 5, "五": 5, "名": 5, "金": 5, "男": 5, "外": 5, "四": 5, "先": 5, "川": 5, "東": 5, "聞": 5, "語": 5, "九": 5, "食": 5, "八": 5, "水": 5, "天": 5, "木": 5, "六": 5, "万": 5, "白": 5, "七": 5, "円": 5, "電": 5, "父": 5, "北": 5, "車": 5, "母": 5, "半": 5, "百": 5, "土": 5, "西": 5, "読": 5, "千": 5, "校": 5, "右": 5, "南": 5, "左": 5, "友": 5, "火": 5, "毎": 5, "雨": 5, "休": 5, "午": 5,

    "言": 4, "手": 4, "自": 4, "者": 4, "事": 4, "思": 4, "会": 4, "家": 4, "的": 4, "方": 4, "地": 4, "目": 4, "場": 4, "代": 4, "私": 4, "立": 4, "物": 4, "田": 4, "体": 4, "動": 4, "社": 4, "知": 4, "理": 4, "同": 4, "心": 4, "発": 4, "作": 4, "新": 4, "世": 4, "度": 4, "明": 4, "力": 4, "意": 4, "用": 4, "主": 4, "通": 4, "文": 4, "屋": 4, "業": 4, "持": 4, "道": 4, "身": 4, "不": 4, "口": 4, "多": 4, "野": 4, "考": 4, "開": 4, "教": 4, "近": 4, "以": 4, "問": 4, "正": 4, "真": 4, "味": 4, "界": 4, "無": 4, "少": 4, "海": 4, "切": 4, "重": 4, "集": 4, "員": 4, "公": 4, "画": 4, "死": 4, "安": 4, "親": 4, "強": 4, "使": 4, "朝": 4, "題": 4, "仕": 4, "京": 4, "足": 4, "品": 4, "着": 4, "別": 4, "音": 4, "元": 4,
    "特": 4, "風": 4, "夜": 4, "空": 4, "有": 4, "起": 4, "運": 4, "料": 4, "楽": 4, "色": 4, "帰": 4, "歩": 4, "悪": 4, "広": 4, "店": 4, "町": 4, "住": 4, "売": 4, "待": 4, "古": 4, "始": 4, "終": 4, "計": 4, "院": 4, "送": 4, "族": 4, "映": 4, "買": 4, "病": 4, "早": 4, "質": 4, "台": 4, "室": 4, "可": 4, "建": 4, "転": 4, "医": 4, "止": 4, "字": 4, "工": 4, "急": 4, "図": 4, "黒": 4, "花": 4, "英": 4, "走": 4, "青": 4, "答": 4, "紙": 4, "歌": 4, "注": 4, "赤": 4, "春": 4, "館": 4, "旅": 4, "験": 4, "写": 4, "去": 4, "研": 4, "飲": 4, "肉": 4, "服": 4, "銀": 4, "茶": 4, "究": 4, "洋": 4, "兄": 4, "秋": 4, "堂": 4, "週": 4, "習": 4, "試": 4, "夏": 4, "弟": 4, "鳥": 4, "犬": 4, "夕": 4, "魚": 4, "借": 4, "飯": 4,
    "駅": 4, "昼": 4, "冬": 4, "姉": 4, "曜": 4, "漢": 4, "牛": 4, "妹": 4, "貸": 4, "勉": 4,

    "合": 3, "部": 3, "彼": 3, "内": 3, "実": 3, "当": 3, "戦": 3, "性": 3, "対": 3, "関": 3, "感": 3, "定": 3, "政": 3, "取": 3, "所": 3, "現": 3, "最": 3, "化": 3, "民": 3, "相": 3, "法": 3, "全": 3, "情": 3, "向": 3, "平": 3, "成": 3, "経": 3, "信": 3, "面": 3, "連": 3, "原": 3, "顔": 3, "機": 3, "次": 3, "数": 3, "美": 3, "回": 3, "表": 3, "声": 3, "報": 3, "要": 3, "変": 3, "神": 3, "記": 3, "和": 3, "引": 3, "治": 3, "決": 3, "太": 3, "込": 3, "受": 3, "解": 3, "市": 3, "期": 3, "様": 3, "活": 3, "頭": 3, "組": 3, "指": 3, "説": 3, "能": 3, "葉": 3, "流": 3, "然": 3, "初": 3, "在": 3, "調": 3, "笑": 3, "議": 3, "直": 3, "夫": 3, "選": 3, "権": 3, "利": 3, "制": 3, "続": 3, "石": 3, "進": 3, "伝": 3, "加": 3,
    "助": 3, "点": 3, "産": 3, "務": 3, "件": 3, "命": 3, "番": 3, "落": 3, "付": 3, "得": 3, "好": 3, "違": 3, "殺": 3, "置": 3, "返": 3, "論": 3, "際": 3, "歳": 3, "反": 3, "形": 3, "光": 3, "首": 3, "勝": 3, "必": 3, "係": 3, "由": 3, "愛": 3, "都": 3, "放": 3, "確": 3, "過": 3, "約": 3, "馬": 3, "状": 3, "想": 3, "官": 3, "交": 3, "米": 3, "配": 3, "若": 3, "資": 3, "常": 3, "果": 3, "呼": 3, "共": 3, "残": 3, "判": 3, "役": 3, "他": 3, "術": 3, "支": 3, "両": 3, "乗": 3, "済": 3, "供": 3, "格": 3, "打": 3, "御": 3, "断": 3, "式": 3, "師": 3, "告": 3, "深": 3, "存": 3, "争": 3, "覚": 3, "側": 3, "飛": 3, "参": 3, "突": 3, "容": 3, "育": 3, "構": 3, "認": 3, "位": 3, "達": 3, "守": 3, "満": 3, "消": 3, "任": 3,
    "居": 3, "予": 3, "路": 3, "座": 3, "客": 3, "船": 3, "追": 3, "背": 3, "観": 3, "誰": 3, "息": 3, "失": 3, "老": 3, "良": 3, "示": 3, "号": 3, "職": 3, "王": 3, "識": 3, "警": 3, "優": 3, "投": 3, "局": 3, "難": 3, "種": 3, "念": 3, "寄": 3, "商": 3, "害": 3, "頼": 3, "横": 3, "増": 3, "差": 3, "苦": 3, "収": 3, "段": 3, "俺": 3, "渡": 3, "与": 3, "演": 3, "備": 3, "申": 3, "例": 3, "働": 3, "景": 3, "抜": 3, "遠": 3, "絶": 3, "負": 3, "福": 3, "球": 3, "酒": 3, "君": 3, "察": 3, "望": 3, "婚": 3, "単": 3, "押": 3, "割": 3, "限": 3, "戻": 3, "科": 3, "求": 3, "談": 3, "降": 3, "妻": 3, "岡": 3, "熱": 3, "浮": 3, "等": 3, "末": 3, "幸": 3, "草": 3, "越": 3, "登": 3, "類": 3, "未": 3, "規": 3, "精": 3, "抱": 3,
    "労": 3, "処": 3, "退": 3, "費": 3, "非": 3, "喜": 3, "娘": 3, "逃": 3, "探": 3, "犯": 3, "薬": 3, "園": 3, "疑": 3, "緒": 3, "静": 3, "具": 3, "席": 3, "速": 3, "舞": 3, "宿": 3, "程": 3, "倒": 3, "寝": 3, "宅": 3, "絵": 3, "破": 3, "庭": 3, "婦": 3, "余": 3, "訪": 3, "冷": 3, "暮": 3, "腹": 3, "危": 3, "許": 3, "似": 3, "険": 3, "財": 3, "遊": 3, "雑": 3, "恐": 3, "値": 3, "暗": 3, "積": 3, "夢": 3, "痛": 3, "富": 3, "刻": 3, "鳴": 3, "欲": 3, "途": 3, "曲": 3, "耳": 3, "完": 3, "願": 3, "罪": 3, "陽": 3, "亡": 3, "散": 3, "掛": 3, "昨": 3, "怒": 3, "留": 3, "礼": 3, "列": 3, "雪": 3, "払": 3, "給": 3, "敗": 3, "捕": 3, "忘": 3, "晴": 3, "因": 3, "折": 3, "迎": 3, "悲": 3, "港": 3, "責": 3, "除": 3, "困": 3,
    "閉": 3, "吸": 3, "髪": 3, "束": 3, "眠": 3, "易": 3, "窓": 3, "祖": 3, "勤": 3, "昔": 3, "便": 3, "適": 3, "吹": 3, "候": 3, "怖": 3, "辞": 3, "否": 3, "遅": 3, "煙": 3, "徒": 3, "欠": 3, "迷": 3, "洗": 3, "互": 3, "才": 3, "更": 3, "歯": 3, "盗": 3, "慣": 3, "晩": 3, "箱": 3, "到": 3, "頂": 3, "杯": 3, "皆": 3, "招": 3, "寒": 3, "恥": 3, "疲": 3, "貧": 3, "猫": 3, "誤": 3, "努": 3, "幾": 3, "賛": 3, "偶": 3, "忙": 3, "泳": 3, "靴": 3, "偉": 3,

    "軍": 2, "兵": 2, "島": 2, "村": 2, "門": 2, "戸": 2, "武": 2, "城": 2, "総": 2, "団": 2, "線": 2, "設": 2, "勢": 2, "党": 2, "史": 2, "営": 2, "府": 2, "巻": 2, "介": 2, "蔵": 2, "造": 2, "根": 2, "寺": 2, "査": 2, "将": 2, "改": 2, "県": 2, "泉": 2, "像": 2, "細": 2, "谷": 2, "奥": 2, "再": 2, "血": 2, "算": 2, "象": 2, "清": 2, "技": 2, "州": 2, "領": 2, "橋": 2, "芸": 2, "型": 2, "香": 2, "量": 2, "久": 2, "境": 2, "階": 2, "区": 2, "波": 2, "移": 2, "域": 2, "周": 2, "接": 2, "鉄": 2, "頃": 2, "材": 2, "個": 2, "協": 2, "各": 2, "帯": 2, "歴": 2, "編": 2, "裏": 2, "比": 2, "坂": 2, "装": 2, "省": 2, "税": 2, "競": 2, "囲": 2, "辺": 2, "河": 2, "極": 2, "防": 2, "低": 2, "林": 2, "導": 2, "森": 2, "丸": 2,
    "胸": 2, "陸": 2, "療": 2, "諸": 2, "管": 2, "仲": 2, "革": 2, "担": 2, "効": 2, "賞": 2, "星": 2, "復": 2, "片": 2, "並": 2, "底": 2, "温": 2, "軽": 2, "録": 2, "腰": 2, "著": 2, "乱": 2, "章": 2, "殿": 2, "布": 2, "角": 2, "仏": 2, "永": 2, "誌": 2, "減": 2, "略": 2, "準": 2, "委": 2, "令": 2, "刊": 2, "焼": 2, "里": 2, "圧": 2, "額": 2, "印": 2, "池": 2, "臣": 2, "庫": 2, "農": 2, "板": 2, "恋": 2, "羽": 2, "専": 2, "逆": 2, "腕": 2, "短": 2, "普": 2, "岩": 2, "竹": 2, "児": 2, "毛": 2, "版": 2, "宇": 2, "況": 2, "被": 2, "岸": 2, "超": 2, "豊": 2, "含": 2, "植": 2, "補": 2, "暴": 2, "課": 2, "跡": 2, "触": 2, "玉": 2, "震": 2, "億": 2, "肩": 2, "劇": 2, "刺": 2, "述": 2, "輪": 2, "浅": 2, "純": 2, "薄": 2,
    "阪": 2, "韓": 2, "固": 2, "巨": 2, "講": 2, "般": 2, "湯": 2, "捨": 2, "衣": 2, "替": 2, "央": 2, "骨": 2, "齢": 2, "照": 2, "層": 2, "弱": 2, "築": 2, "脳": 2, "航": 2, "快": 2, "翌": 2, "旧": 2, "筆": 2, "換": 2, "群": 2, "爆": 2, "捜": 2, "油": 2, "叫": 2, "伸": 2, "承": 2, "雲": 2, "練": 2, "紹": 2, "包": 2, "庁": 2, "測": 2, "占": 2, "混": 2, "倍": 2, "乳": 2, "荒": 2, "詰": 2, "栄": 2, "床": 2, "則": 2, "禁": 2, "順": 2, "枚": 2, "厚": 2, "皮": 2, "輸": 2, "濃": 2, "簡": 2, "孫": 2, "丈": 2, "黄": 2, "届": 2, "絡": 2, "採": 2, "傾": 2, "鼻": 2, "宝": 2, "患": 2, "延": 2, "律": 2, "希": 2, "甘": 2, "湾": 2, "沈": 2, "販": 2, "欧": 2, "砂": 2, "尊": 2, "紅": 2, "複": 2, "泊": 2, "荷": 2, "枝": 2, "依": 2,
    "幼": 2, "斬": 2, "勇": 2, "昇": 2, "寿": 2, "菜": 2, "季": 2, "液": 2, "券": 2, "祭": 2, "袋": 2, "燃": 2, "毒": 2, "札": 2, "狙": 2, "脇": 2, "卒": 2, "副": 2, "敬": 2, "針": 2, "拝": 2, "浴": 2, "悩": 2, "汚": 2, "灯": 2, "坊": 2, "尻": 2, "涙": 2, "停": 2, "了": 2, "汗": 2, "郵": 2, "幅": 2, "童": 2, "虫": 2, "埋": 2, "舟": 2, "闇": 2, "棒": 2, "貨": 2, "肌": 2, "臓": 2, "塩": 2, "均": 2, "湖": 2, "損": 2, "膝": 2, "辛": 2, "双": 2, "軒": 2, "績": 2, "干": 2, "姓": 2, "掘": 2, "籍": 2, "珍": 2, "訓": 2, "預": 2, "署": 2, "漁": 2, "緑": 2, "畳": 2, "咲": 2, "貿": 2, "踊": 2, "封": 2, "兆": 2, "柱": 2, "駐": 2, "祝": 2, "炭": 2, "柔": 2, "雇": 2, "乾": 2, "鋭": 2, "氷": 2, "隅": 2, "冊": 2, "糸": 2, "募": 2,
    "硬": 2, "塗": 2, "憎": 2, "泥": 2, "脂": 2, "粉": 2, "詞": 2, "筒": 2, "掃": 2, "塔": 2, "賢": 2, "拾": 2, "麦": 2, "刷": 2, "卵": 2, "械": 2, "皿": 2, "祈": 2, "灰": 2, "召": 2, "溶": 2, "磨": 2, "粒": 2, "喫": 2, "机": 2, "貯": 2, "匹": 2, "綿": 2, "贈": 2, "凍": 2, "瓶": 2, "帽": 2, "涼": 2, "秒": 2, "湿": 2, "蒸": 2, "菓": 2, "耕": 2, "鉱": 2, "膚": 2, "胃": 2, "挟": 2, "郊": 2, "銅": 2, "鈍": 2, "貝": 2, "缶": 2, "枯": 2, "滴": 2, "符": 2, "畜": 2, "軟": 2, "濯": 2, "隻": 2, "伺": 2, "沸": 2, "曇": 2, "肯": 2, "燥": 2, "零": 2,

    "郎": 1, "結": 1, "氏": 1, "衛": 1, "第": 1, "保": 1, "義": 1, "吉": 1, "士": 1, "藤": 1, "井": 1, "江": 1, "張": 1, "松": 1, "応": 1, "視": 1, "態": 1, "姿": 1, "皇": 1, "宮": 1, "離": 1, "基": 1, "隊": 1, "素": 1, "価": 1, "撃": 1, "振": 1, "証": 1, "派": 1, "僕": 1, "佐": 1, "紀": 1, "統": 1, "器": 1, "異": 1, "護": 1, "条": 1, "独": 1, "源": 1, "影": 1, "眼": 1, "企": 1, "津": 1, "案": 1, "策": 1, "宗": 1, "提": 1, "昭": 1, "密": 1, "司": 1, "検": 1, "康": 1, "沢": 1, "秀": 1, "興": 1, "率": 1, "評": 1, "監": 1, "崎": 1, "鮮": 1, "激": 1, "徳": 1, "挙": 1, "志": 1, "敷": 1, "系": 1, "織": 1, "製": 1, "端": 1, "遺": 1, "房": 1, "街": 1, "尾": 1, "株": 1, "従": 1, "敵": 1, "展": 1, "描": 1, "修": 1, "我": 1,
    "載": 1, "響": 1, "秘": 1, "攻": 1, "健": 1, "裁": 1, "隠": 1, "環": 1, "援": 1, "故": 1, "幕": 1, "督": 1, "倉": 1, "施": 1, "嫌": 1, "継": 1, "障": 1, "貴": 1, "整": 1, "衆": 1, "及": 1, "盛": 1, "玄": 1, "恵": 1, "授": 1, "弾": 1, "養": 1, "驚": 1, "奈": 1, "推": 1, "樹": 1, "為": 1, "雄": 1, "刀": 1, "弁": 1, "妙": 1, "模": 1, "抗": 1, "級": 1, "瞬": 1, "称": 1, "華": 1, "傷": 1, "闘": 1, "筋": 1, "訳": 1, "射": 1, "善": 1, "黙": 1, "柄": 1, "刑": 1, "節": 1, "脱": 1, "厳": 1, "博": 1, "陣": 1, "奇": 1, "忠": 1, "染": 1, "微": 1, "標": 1, "縁": 1, "壁": 1, "駆": 1, "麻": 1, "甲": 1, "藩": 1, "迫": 1, "踏": 1, "討": 1, "聖": 1, "典": 1, "剣": 1, "症": 1, "納": 1, "弥": 1, "融": 1, "浜": 1, "郷": 1, "惑": 1,
    "柳": 1, "拠": 1, "奉": 1, "壊": 1, "益": 1, "句": 1, "属": 1, "功": 1, "帝": 1, "賀": 1, "堀": 1, "創": 1, "泣": 1, "憶": 1, "幹": 1, "露": 1, "矢": 1, "握": 1, "儀": 1, "聴": 1, "襲": 1, "徴": 1, "丁": 1, "憲": 1, "閣": 1, "救": 1, "陰": 1, "繰": 1, "那": 1, "操": 1, "騒": 1, "己": 1, "魔": 1, "撮": 1, "携": 1, "隣": 1, "宣": 1, "遣": 1, "訴": 1, "茂": 1, "釣": 1, "批": 1, "誘": 1, "核": 1, "哲": 1, "豪": 1, "締": 1, "鹿": 1, "就": 1, "滅": 1, "仰": 1, "瀬": 1, "致": 1, "伏": 1, "杉": 1, "審": 1, "避": 1, "揺": 1, "浦": 1, "至": 1, "裕": 1, "盟": 1, "執": 1, "崩": 1, "鬼": 1, "酸": 1, "拡": 1, "銃": 1, "維": 1, "縄": 1, "詩": 1, "廃": 1, "充": 1, "鏡": 1, "仮": 1, "吐": 1, "請": 1, "眺": 1, "沖": 1, "躍": 1,
    "威": 1, "屈": 1, "勘": 1, "徹": 1, "斎": 1, "謝": 1, "艦": 1, "催": 1, "舎": 1, "仁": 1, "衝": 1, "脚": 1, "虎": 1, "潮": 1, "穴": 1, "怪": 1, "仙": 1, "輝": 1, "緊": 1, "唇": 1, "忍": 1, "狂": 1, "奪": 1, "診": 1, "竜": 1, "債": 1, "鈴": 1, "僧": 1, "掲": 1, "伯": 1, "熊": 1, "浪": 1, "梅": 1, "看": 1, "俊": 1, "摘": 1, "項": 1, "霊": 1, "垣": 1, "慢": 1, "扱": 1, "渉": 1, "如": 1, "縮": 1, "詳": 1, "旦": 1, "慮": 1, "雅": 1, "砲": 1, "謀": 1, "懐": 1, "愚": 1, "舌": 1, "駄": 1, "奴": 1, "豆": 1, "又": 1, "銭": 1, "抑": 1, "侍": 1, "宙": 1, "範": 1, "潜": 1, "酔": 1, "呂": 1, "還": 1, "丹": 1, "亜": 1, "亀": 1, "沼": 1, "巡": 1, "臭": 1, "慶": 1, "距": 1, "釈": 1, "侵": 1, "僚": 1, "悟": 1, "隆": 1, "裂": 1,
    "尋": 1, "旗": 1, "羅": 1, "揮": 1, "票": 1, "稲": 1, "胞": 1, "懸": 1, "稿": 1, "塚": 1, "盤": 1, "災": 1, "曹": 1, "尽": 1, "嫁": 1, "繁": 1, "即": 1, "帳": 1, "飾": 1, "沿": 1, "獲": 1, "伴": 1, "唐": 1, "狭": 1, "添": 1, "剤": 1, "魅": 1, "契": 1, "邪": 1, "挑": 1, "免": 1, "爵": 1, "択": 1, "廊": 1, "析": 1, "輩": 1, "敏": 1, "鶴": 1, "虚": 1, "往": 1, "趣": 1, "烈": 1, "索": 1, "匂": 1, "摩": 1, "菊": 1, "滑": 1, "沙": 1, "裸": 1, "孝": 1, "綱": 1, "邸": 1, "邦": 1, "揚": 1, "卓": 1, "騎": 1, "墓": 1, "姫": 1, "孔": 1, "耐": 1, "須": 1, "臨": 1, "献": 1, "脈": 1, "芝": 1, "唱": 1, "亭": 1, "誕": 1, "貫": 1, "偽": 1, "奮": 1, "桜": 1, "熟": 1, "排": 1, "透": 1, "棄": 1, "削": 1, "奏": 1, "幻": 1, "麗": 1,
    "逮": 1, "誠": 1, "炎": 1, "椅": 1, "寛": 1, "斉": 1, "穂": 1, "兼": 1, "飼": 1, "促": 1, "尚": 1, "彩": 1, "暖": 1, "俗": 1, "較": 1, "傍": 1, "肝": 1, "畑": 1, "峰": 1, "抵": 1, "恩": 1, "誇": 1, "網": 1, "渋": 1, "魂": 1, "牧": 1, "控": 1, "紛": 1, "戒": 1, "没": 1, "既": 1, "股": 1, "脅": 1, "征": 1, "覆": 1, "郡": 1, "丘": 1, "佳": 1, "叔": 1, "託": 1, "哀": 1, "肥": 1, "朗": 1, "慎": 1, "悠": 1, "眉": 1, "拒": 1, "概": 1, "顧": 1, "腐": 1, "挨": 1, "孤": 1, "拶": 1, "却": 1, "賊": 1, "荘": 1, "匠": 1, "悔": 1, "獄": 1, "滞": 1, "遇": 1, "淡": 1, "購": 1, "併": 1, "崇": 1, "唯": 1, "垂": 1, "岐": 1, "俳": 1, "斜": 1, "嬢": 1, "陥": 1, "償": 1, "鑑": 1, "勧": 1, "葬": 1, "焦": 1, "剛": 1, "膨": 1, "廷": 1,
    "紫": 1, "銘": 1, "鎌": 1, "菌": 1, "稼": 1, "譲": 1, "随": 1, "猛": 1, "遂": 1, "冒": 1, "泰": 1, "翼": 1, "凄": 1, "序": 1, "扉": 1, "是": 1, "寸": 1, "賃": 1, "偵": 1, "澄": 1, "殊": 1, "緩": 1, "頑": 1, "紋": 1, "糖": 1, "煮": 1, "芳": 1, "惨": 1, "歓": 1, "虐": 1, "喉": 1, "旨": 1, "凝": 1, "圏": 1, "拭": 1, "涯": 1, "貞": 1, "堅": 1, "倫": 1, "壇": 1, "呉": 1, "暇": 1, "貌": 1, "塞": 1, "噴": 1, "婆": 1, "岳": 1, "蹴": 1, "鍵": 1, "膳": 1, "尺": 1, "罰": 1, "漏": 1, "朱": 1, "覧": 1, "漂": 1, "汁": 1, "寂": 1, "嘆": 1, "禅": 1, "浄": 1, "酷": 1, "刃": 1, "漫": 1, "霧": 1, "暑": 1, "棚": 1, "袖": 1, "壮": 1, "旬": 1, "彫": 1, "需": 1, "鎖": 1, "潰": 1, "縦": 1, "粧": 1, "慌": 1, "穏": 1, "枠": 1, "謎": 1,
    "誉": 1, "逸": 1, "駒": 1, "惜": 1, "措": 1, "晶": 1, "琴": 1, "摂": 1, "拍": 1, "稽": 1, "礎": 1, "遭": 1, "掌": 1, "鍋": 1, "弓": 1, "克": 1, "据": 1, "胆": 1, "跳": 1, "縛": 1, "鎮": 1, "雷": 1, "恨": 1, "顕": 1, "殖": 1, "寧": 1, "湧": 1, "棋": 1, "巧": 1, "浸": 1, "桃": 1, "隔": 1, "班": 1, "甚": 1, "妊": 1, "祉": 1, "獣": 1, "疾": 1, "塾": 1, "潟": 1, "撲": 1, "塊": 1, "絞": 1, "履": 1, "苗": 1, "芋": 1, "冗": 1, "陶": 1, "励": 1, "陳": 1, "猿": 1, "葛": 1, "傘": 1, "啓": 1, "劣": 1, "撤": 1, "殴": 1, "盾": 1, "衰": 1, "滝": 1, "慰": 1, "蛇": 1, "梨": 1, "癖": 1, "潤": 1, "鉢": 1, "戯": 1, "腸": 1, "偏": 1, "巣": 1, "宴": 1, "炉": 1, "棟": 1, "洞": 1, "狩": 1, "陛": 1, "磁": 1, "潔": 1, "膜": 1, "乏": 1,
    "祥": 1, "曽": 1, "舗": 1, "抽": 1, "睡": 1, "賭": 1, "括": 1, "貢": 1, "犠": 1, "粗": 1, "卑": 1, "貼": 1, "拉": 1, "牲": 1, "帆": 1, "挿": 1, "翻": 1, "羊": 1, "枕": 1, "錯": 1, "謙": 1, "珠": 1, "蓄": 1, "拓": 1, "鼓": 1, "粋": 1, "尉": 1, "后": 1, "粘": 1, "披": 1, "徐": 1, "悦": 1, "堪": 1, "冠": 1, "愉": 1, "尿": 1, "顎": 1, "誓": 1, "憂": 1, "簿": 1, "糧": 1, "架": 1, "芽": 1, "軸": 1, "苛": 1, "蓋": 1, "盆": 1, "凶": 1, "妃": 1, "庶": 1, "秩": 1, "裾": 1, "幽": 1, "凡": 1, "漠": 1, "拙": 1, "恒": 1, "暦": 1, "腫": 1, "峠": 1, "宰": 1, "蛮": 1, "窮": 1, "擦": 1, "爪": 1, "稚": 1, "辱": 1, "嵐": 1, "憤": 1, "癒": 1, "鬱": 1, "疎": 1, "雰": 1, "彰": 1, "肺": 1, "傑": 1, "拘": 1, "頻": 1, "緯": 1, "妖": 1,
    "豚": 1, "藍": 1, "矛": 1, "鍛": 1, "繊": 1, "縫": 1, "把": 1, "楼": 1, "捉": 1, "漬": 1, "紳": 1, "飽": 1, "宛": 1, "閥": 1, "旋": 1, "坪": 1, "崖": 1, "叱": 1, "鶏": 1, "峡": 1, "溝": 1, "朴": 1, "軌": 1, "瓦": 1, "喪": 1, "墨": 1, "疫": 1, "遍": 1, "濁": 1, "扇": 1, "拳": 1, "乙": 1, "酵": 1, "堤": 1, "阻": 1, "桑": 1, "虜": 1, "乞": 1, "恭": 1, "鐘": 1, "剰": 1, "慈": 1, "径": 1, "培": 1, "擁": 1, "郭": 1, "呪": 1, "砕": 1, "汰": 1, "勃": 1, "翁": 1, "絹": 1, "譜": 1, "陵": 1, "痴": 1, "笛": 1, "昧": 1, "訟": 1, "唾": 1, "肪": 1, "塀": 1, "碁": 1, "敢": 1, "塁": 1, "暁": 1, "胴": 1, "謡": 1, "飢": 1, "欄": 1, "艶": 1, "痕": 1, "怠": 1, "欺": 1, "弦": 1, "泡": 1, "諦": 1, "伐": 1, "餅": 1, "寮": 1, "厄": 1,
    "奔": 1, "瞳": 1, "昆": 1, "椎": 1, "懇": 1, "唄": 1, "渦": 1, "襟": 1, "吟": 1, "覇": 1, "衡": 1, "呈": 1, "隙": 1, "淫": 1, "娠": 1, "循": 1, "懲": 1, "錦": 1, "猟": 1, "幣": 1, "附": 1, "箇": 1, "醜": 1, "箸": 1, "戚": 1, "喚": 1, "紺": 1, "某": 1, "鋼": 1, "褒": 1, "赴": 1, "媒": 1, "妬": 1, "遮": 1, "窯": 1, "侯": 1, "釜": 1, "茎": 1, "蔑": 1, "嗅": 1, "壌": 1, "蜜": 1, "尼": 1, "肢": 1, "赦": 1, "酬": 1, "戴": 1, "詠": 1, "斗": 1, "宜": 1, "殻": 1, "墳": 1, "炊": 1, "碑": 1, "痩": 1, "但": 1, "奨": 1, "践": 1, "滋": 1, "儒": 1, "薦": 1, "怨": 1, "栽": 1, "刈": 1, "閑": 1, "錠": 1, "扶": 1, "妥": 1, "妨": 1, "醒": 1, "詣": 1, "胎": 1, "窟": 1, "巾": 1, "蜂": 1, "忌": 1, "骸": 1, "弄": 1, "嫉": 1, "粛": 1,
    "罵": 1, "囚": 1, "鉛": 1, "搭": 1, "諭": 1, "璧": 1, "阜": 1, "喝": 1, "享": 1, "騰": 1, "嗣": 1, "勅": 1, "篤": 1, "勲": 1, "埼": 1, "伎": 1, "曖": 1, "詐": 1, "餌": 1, "岬": 1, "暫": 1, "爽": 1, "肖": 1, "詮": 1, "諾": 1, "柿": 1, "芯": 1, "綻": 1, "訂": 1, "汽": 1, "薫": 1, "隷": 1, "俵": 1, "遷": 1, "枢": 1, "肘": 1, "麓": 1, "憧": 1, "帥": 1, "漆": 1, "酌": 1, "頓": 1, "賠": 1, "渇": 1, "慕": 1, "婿": 1, "妄": 1, "慨": 1, "匿": 1, "渓": 1, "侮": 1, "髄": 1, "穀": 1, "薪": 1, "轄": 1, "洪": 1, "牙": 1, "咽": 1, "迅": 1, "該": 1, "逐": 1, "嘲": 1, "墜": 1, "臆": 1, "餓": 1, "挫": 1, "錬": 1, "桟": 1, "溺": 1, "賄": 1, "盲": 1, "鯨": 1, "侶": 1, "艇": 1, "丼": 1, "堕": 1, "瘍": 1, "槽": 1, "憩": 1, "僅": 1,
    "閲": 1, "柵": 1, "畔": 1, "睦": 1, "唆": 1, "悼": 1, "吏": 1, "穫": 1, "酢": 1, "賜": 1, "腎": 1, "梗": 1, "瑠": 1, "羨": 1, "搬": 1, "剖": 1, "酎": 1, "畿": 1, "宵": 1, "拐": 1, "醸": 1, "猶": 1, "諮": 1, "畏": 1, "泌": 1, "愁": 1, "逝": 1, "朽": 1, "硫": 1, "瞭": 1, "擬": 1, "叙": 1, "弊": 1, "累": 1, "煩": 1, "踪": 1, "藻": 1, "蚊": 1, "栃": 1, "且": 1, "鋳": 1, "蔽": 1, "茨": 1, "棺": 1, "慄": 1, "傲": 1, "硝": 1, "舶": 1, "租": 1, "倣": 1, "謹": 1, "抹": 1, "虹": 1, "捻": 1, "娯": 1, "臼": 1, "喩": 1, "萎": 1, "蛍": 1, "窒": 1, "腺": 1, "桁": 1, "玩": 1, "冶": 1, "羞": 1, "栓": 1, "惧": 1, "寡": 1, "畝": 1, "淑": 1, "嫡": 1, "屯": 1, "糾": 1, "遡": 1, "陪": 1, "雌": 1, "舷": 1, "霜": 1, "殉": 1, "紡": 1,
    "貪": 1, "庸": 1, "韻": 1, "繕": 1, "搾": 1, "刹": 1, "采": 1, "堆": 1, "禍": 1, "煎": 1, "姻": 1, "斑": 1, "冥": 1, "抄": 1, "拷": 1, "遜": 1, "旺": 1, "准": 1, "勾": 1, "廉": 1, "礁": 1, "壱": 1, "麺": 1, "升": 1, "卸": 1, "耗": 1, "謁": 1, "璃": 1, "坑": 1, "串": 1, "弔": 1, "賓": 1, "塡": 1, "痢": 1, "嚇": 1, "濫": 1, "俸": 1, "箋": 1, "凸": 1, "脊": 1, "詔": 1, "緻": 1, "凹": 1, "罷": 1, "漸": 1, "賦": 1, "弧": 1, "褐": 1, "辣": 1, "摯": 1, "汎": 1, "斥": 1, "厘": 1, "矯": 1, "毀": 1, "窃": 1, "遵": 1, "賂": 1, "惰": 1, "蚕": 1, "氾": 1, "諧": 1, "倹": 1, "款": 1, "媛": 1, "憾": 1, "哺": 1, "衷": 1, "彙": 1, "迭": 1, "嘱": 1, "恣": 1, "墾": 1, "逓": 1, "劾": 1, "酪": 1, "沃": 1, "塑": 1, "痘": 1, "憬": 1,
    "朕": 1, "虞": 1, "丙": 1, "斤": 1, "捗": 1, "弐": 1, "訃": 1, "謄": 1, "繭": 1, "璽": 1, "頒": 1, "楷": 1, "剥": 1, "籠": 1, "錮": 1, "頰": 1,
}

JMDICT_ENTITIES = {
    "bra": "Brazilian",
    "hob": "Hokkaidoben",
    "ksb": "Kansaiben",
    "ktb": "Kantouben",
    "kyb": "Kyotoben",
    "kyu": "Kyuushuuben",
    "nab": "Naganoben",
    "osb": "Osakaben",
    "rkb": "Ryuukyuuben",
    "thb": "Touhokuben",
    "tsb": "Tosaben",
    "tsug": "Tsugaruben",
    "agric": "agriculture",
    "anat": "anatomy",
    "archeol": "archeology",
    "archit": "architecture",
    "art": "art, aesthetics",
    "astron": "astronomy",
    "audvid": "audiovisual",
    "aviat": "aviation",
    "baseb": "baseball",
    "biochem": "biochemistry",
    "biol": "biology",
    "bot": "botany",
    "boxing": "boxing",
    "Buddh": "Buddhism",
    "bus": "business",
    "cards": "card games",
    "chem": "chemistry",
    "chmyth": "Chinese mythology",
    "Christn": "Christianity",
    "civeng": "civil engineering",
    "cloth": "clothing",
    "comp": "computing",
    "cryst": "crystallography",
    "dent": "dentistry",
    "ecol": "ecology",
    "econ": "economics",
    "elec": "electricity, elec. eng.",
    "electr": "electronics",
    "embryo": "embryology",
    "engr": "engineering",
    "ent": "entomology",
    "figskt": "figure skating",
    "film": "film",
    "finc": "finance",
    "fish": "fishing",
    "food": "food, cooking",
    "gardn": "gardening, horticulture",
    "genet": "genetics",
    "geogr": "geography",
    "geol": "geology",
    "geom": "geometry",
    "go": "go (game)",
    "golf": "golf",
    "gramm": "grammar",
    "grmyth": "Greek mythology",
    "hanaf": "hanafuda",
    "horse": "horse racing",
    "internet": "Internet",
    "jpmyth": "Japanese mythology",
    "kabuki": "kabuki",
    "law": "law",
    "ling": "linguistics",
    "logic": "logic",
    "MA": "martial arts",
    "mahj": "mahjong",
    "manga": "manga",
    "math": "mathematics",
    "mech": "mechanical engineering",
    "med": "medicine",
    "met": "meteorology",
    "mil": "military",
    "min": "mineralogy",
    "mining": "mining",
    "motor": "motorsport",
    "music": "music",
    "noh": "noh",
    "ornith": "ornithology",
    "paleo": "paleontology",
    "pathol": "pathology",
    "pharm": "pharmacology",
    "phil": "philosophy",
    "photo": "photography",
    "physics": "physics",
    "physiol": "physiology",
    "politics": "politics",
    "print": "printing",
    "prowres": "professional wrestling",
    "psy": "psychiatry",
    "psyanal": "psychoanalysis",
    "psych": "psychology",
    "rail": "railway",
    "rommyth": "Roman mythology",
    "Shinto": "Shinto",
    "shogi": "shogi",
    "ski": "skiing",
    "sports": "sports",
    "stat": "statistics",
    "stockm": "stock market",
    "sumo": "sumo",
    "surg": "surgery",
    "telec": "telecommunications",
    "tradem": "trademark",
    "tv": "television",
    "vet": "veterinary terms",
    "vidg": "video games",
    "zool": "zoology",
    "ateji": "ateji (phonetic) reading",
    "ik": "word containing irregular kana usage",
    "iK": "word containing irregular kanji usage",
    "io": "irregular okurigana usage",
    "oK": "word containing outdated kanji or kanji usage",
    "rK": "rarely used kanji form",
    "sK": "searchonly kanji form",
    "abbr": "abbreviation",
    "arch": "archaic",
    "char": "character",
    "chn": "children's language",
    "col": "colloquial",
    "company": "company name",
    "creat": "creature",
    "dated": "dated term",
    "dei": "deity",
    "derog": "derogatory",
    "doc": "document",
    "euph": "euphemistic",
    "ev": "event",
    "fam": "familiar language",
    "fem": "female term or language",
    "fict": "fiction",
    "form": "formal or literary term",
    "given": "given name or forename, gender not specified",
    "group": "group",
    "hist": "historical term",
    "hon": "honorific or respectful (sonkeigo) language",
    "hum": "humble (kenjougo) language",
    "id": "idiomatic expression",
    "joc": "jocular, humorous term",
    "leg": "legend",
    "msl": "manga slang",
    "male": "male term or language",
    "myth": "mythology",
    "netsl": "Internet slang",
    "obj": "object",
    "obs": "obsolete term",
    "onmim": "onomatopoeic or mimetic word",
    "organization": "organization name",
    "oth": "other",
    "person": "full name of a particular person",
    "place": "place name",
    "poet": "poetical term",
    "pol": "polite (teineigo) language",
    "product": "product name",
    "proverb": "proverb",
    "quote": "quotation",
    "rare": "rare term",
    "relig": "religion",
    "sens": "sensitive",
    "serv": "service",
    "ship": "ship name",
    "sl": "slang",
    "station": "railway station",
    "surname": "family or surname",
    "uk": "word usually written using kana alone",
    "unclass": "unclassified name",
    "vulg": "vulgar expression or word",
    "work": "work of art, literature, music, etc. name",
    "X": "rude or Xrated term (not displayed in educational software)",
    "yoji": "yojijukugo",
    "adjf": "noun or verb acting prenominally",
    "adji": "adjective (keiyoushi)",
    "adjix": "adjective (keiyoushi)  yoi/ii class",
    "adjkari": "'kari' adjective (archaic)",
    "adjku": "'ku' adjective (archaic)",
    "adjna": "adjectival nouns or quasiadjectives (keiyodoshi)",
    "adjnari": "archaic/formal form of naadjective",
    "adjno": "nouns which may take the genitive case particle 'no'",
    "adjpn": "prenoun adjectival (rentaishi)",
    "adjshiku": "'shiku' adjective (archaic)",
    "adjt": "'taru' adjective",
    "adv": "adverb (fukushi)",
    "advto": "adverb taking the 'to' particle",
    "aux": "auxiliary",
    "auxadj": "auxiliary adjective",
    "auxv": "auxiliary verb",
    "conj": "conjunction",
    "cop": "copula",
    "ctr": "counter",
    "exp": "expressions (phrases, clauses, etc.)",
    "int": "interjection (kandoushi)",
    "n": "noun (common) (futsuumeishi)",
    "nadv": "adverbial noun (fukushitekimeishi)",
    "npr": "proper noun",
    "npref": "noun, used as a prefix",
    "nsuf": "noun, used as a suffix",
    "nt": "noun (temporal) (jisoumeishi)",
    "num": "numeric",
    "pn": "pronoun",
    "pref": "prefix",
    "prt": "particle",
    "suf": "suffix",
    "unc": "unclassified",
    "vunspec": "verb unspecified",
    "v1": "Ichidan verb",
    "v1s": "Ichidan verb  kureru special class",
    "v2as": "Nidan verb with 'u' ending (archaic)",
    "v2bk": "Nidan verb (upper class) with 'bu' ending (archaic)",
    "v2bs": "Nidan verb (lower class) with 'bu' ending (archaic)",
    "v2dk": "Nidan verb (upper class) with 'dzu' ending (archaic)",
    "v2ds": "Nidan verb (lower class) with 'dzu' ending (archaic)",
    "v2gk": "Nidan verb (upper class) with 'gu' ending (archaic)",
    "v2gs": "Nidan verb (lower class) with 'gu' ending (archaic)",
    "v2hk": "Nidan verb (upper class) with 'hu/fu' ending (archaic)",
    "v2hs": "Nidan verb (lower class) with 'hu/fu' ending (archaic)",
    "v2kk": "Nidan verb (upper class) with 'ku' ending (archaic)",
    "v2ks": "Nidan verb (lower class) with 'ku' ending (archaic)",
    "v2mk": "Nidan verb (upper class) with 'mu' ending (archaic)",
    "v2ms": "Nidan verb (lower class) with 'mu' ending (archaic)",
    "v2ns": "Nidan verb (lower class) with 'nu' ending (archaic)",
    "v2rk": "Nidan verb (upper class) with 'ru' ending (archaic)",
    "v2rs": "Nidan verb (lower class) with 'ru' ending (archaic)",
    "v2ss": "Nidan verb (lower class) with 'su' ending (archaic)",
    "v2tk": "Nidan verb (upper class) with 'tsu' ending (archaic)",
    "v2ts": "Nidan verb (lower class) with 'tsu' ending (archaic)",
    "v2ws": "Nidan verb (lower class) with 'u' ending and 'we' conjugation (archaic)",
    "v2yk": "Nidan verb (upper class) with 'yu' ending (archaic)",
    "v2ys": "Nidan verb (lower class) with 'yu' ending (archaic)",
    "v2zs": "Nidan verb (lower class) with 'zu' ending (archaic)",
    "v4b": "Yodan verb with 'bu' ending (archaic)",
    "v4g": "Yodan verb with 'gu' ending (archaic)",
    "v4h": "Yodan verb with 'hu/fu' ending (archaic)",
    "v4k": "Yodan verb with 'ku' ending (archaic)",
    "v4m": "Yodan verb with 'mu' ending (archaic)",
    "v4n": "Yodan verb with 'nu' ending (archaic)",
    "v4r": "Yodan verb with 'ru' ending (archaic)",
    "v4s": "Yodan verb with 'su' ending (archaic)",
    "v4t": "Yodan verb with 'tsu' ending (archaic)",
    "v5aru": "Godan verb  aru special class",
    "v5b": "Godan verb with 'bu' ending",
    "v5g": "Godan verb with 'gu' ending",
    "v5k": "Godan verb with 'ku' ending",
    "v5ks": "Godan verb  Iku/Yuku special class",
    "v5m": "Godan verb with 'mu' ending",
    "v5n": "Godan verb with 'nu' ending",
    "v5r": "Godan verb with 'ru' ending",
    "v5ri": "Godan verb with 'ru' ending (irregular verb)",
    "v5s": "Godan verb with 'su' ending",
    "v5t": "Godan verb with 'tsu' ending",
    "v5u": "Godan verb with 'u' ending",
    "v5us": "Godan verb with 'u' ending (special class)",
    "v5uru": "Godan verb  Uru old class verb (old form of Eru)",
    "vi": "intransitive verb",
    "vk": "Kuru verb  special class",
    "vn": "irregular nu verb",
    "vr": "irregular ru verb, plain form ends with ri",
    "vs": "noun or participle which takes the aux. verb suru",
    "vsc": "su verb  precursor to the modern suru",
    "vsi": "suru verb  included",
    "vss": "suru verb  special class",
    "vt": "transitive verb",
    "vz": "Ichidan verb  zuru verb (alternative form of jiru verbs)",
    "gikun": "gikun (meaning as reading) or jukujikun (special kanji reading)",
    "ok": "outdated or obsolete kana usage",
    "rk": "rarely used kana form",
    "sk": "searchonly kana form",
}
